name: CI

on: 
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt update && sudo apt install gcc-arm-none-eabi 

    - name: Build project
      run: |
        make

    - name: Release Firmware
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: buid/stm32f407vet6.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
